<?php
const CROPPERJS_VERSION = '0.5.5';

/**
 * Implements hook_libraries_info().
 */
function easy_frames_libraries_info() {
    $libraries['cropper'] = array(
        'name' => 'Cropper library',
        'vendor url' => 'http://fengyuanchen.github.io/cropper/',
        'download url' => 'https://github.com/fengyuanchen/cropperjs',
        'version arguments' => array(
            'file' => 'dist/cropper.min.js',
            'pattern' => '/Cropper v(\d+\.+\d.+\d+)/',
            'lines' => 5,
        ),
        'files' => array(
            'js' => array(
                'dist/cropper.min.js',
            ),
            'css' => array(
                'dist/cropper.min.css'
            ),
        ),
    );

    return $libraries;
}


/**
 * Implements hook_requirements().
 */
function easy_frames_requirements($phase) {
    module_load_include('inc', 'easy_frames', 'inc/common');
    $requirements = array();

    if ($phase == 'runtime') {
        $requirements = easy_frames_check_version(CROPPERJS_VERSION);
    }

    return $requirements;
}

/**
 * Implements hook_imagecache_actions().
 */
function easy_frames_image_effect_info() {
    $effects = array();
    $effects['easy_frames_frame'] = array(
        'label' => t('Easy frames'),
        'help' => t('Upload frame image, then use crop tool to select internal <em>transparent</em> square of frame.'),
        'effect callback' => 'easy_frames_frame_effect',
        'dimensions passthrough' => TRUE,
        'form callback' => 'easy_frames_frame_form',
        'summary theme' => 'easy_frames_frame_summary',
    );
    return $effects;
}

function easy_frames_frame_form($action) {
    libraries_load('cropper');
    drupal_add_js(drupal_get_path('module', 'easy_frames') . '/js/main.js');

    $form = array();
    dpm($action);

    $form['frame_image'] = array(
        '#type' => 'managed_file',
        '#name' => 'frame_file',
        '#title' => t('Frame image'),
        '#size' => 40,
        '#description' => t("After uploading image, select internal empty space of the frame."),
        '#upload_location' => 'public://',
        '#default_value' => (isset($action['frame_image']) && $action['frame_image']) ? $action['frame_image'] : '',
        '#theme' => 'easy_frames_frame_upload',
    );

    $form['frame_thickness'] = array(
        '#type' => 'textfield',
        '#title' => t('Frame thickness'),
        '#default_value' => (isset($action['frame_thickness']) && $action['frame_thickness']) ? $action['frame_thickness'] : '100',
        '#size' => 3,
        '#field_suffix' => '%',
        '#description' => t('Enter frame thickness in percent of original. Values from 50 to 200 are practical. <em>Notice that if frame image is smaller then image it is applied to, it will be downscaled to the size of the image first.</em>'),
    );

    $form['downscale_image'] = array(
        '#type' => 'checkbox',
        '#title' => t('Downscale image'),
        '#description' => t('By default image will be fitted inside frame, if not checked frame will be drawn outside of image, making it bigger'),
        '#default_value' => (isset($action['downscale_image'])) ? $action['downscale_image'] : 1,
    );

    $form['frame_left'] = array(
        '#title' =>  t('frame_left'),
        '#default_value' => (isset($action['frame_left']) && $action['frame_left']) ? $action['frame_left'] : '',
        '#type' => 'hidden',
    );
    $form['frame_top'] = array(
        '#title' =>  t('frame_top'),
        '#default_value' => (isset($action['frame_top']) && $action['frame_top']) ? $action['frame_top'] : '',
        '#type' => 'hidden',
    );
    $form['frame_right'] = array(
        '#title' =>  t('frame_right'),
        '#default_value' => (isset($action['frame_right']) && $action['frame_right']) ? $action['frame_right'] : '',
        '#type' => 'hidden',
    );
    $form['frame_bottom'] = array(
        '#title' =>  t('frame_bottom'),
        '#default_value' => (isset($action['frame_bottom']) && $action['frame_bottom']) ? $action['frame_bottom'] : '',
        '#type' => 'hidden',
    );

    $form['#submit'][] = 'easy_frame_submit_callback';

    return $form;
}


/**
 * Implements theme_mymodule_thumb_upload theme callback.
 */
function theme_easy_frames_frame_upload($variables) {
    $element = $variables['element'];

    $output = '<div class="image-widget form-managed-file clearfix easy-frames-frame-image">';

    if ($element['fid']['#value'] != 0) {
        $output .= '<script type="text/javascript">jQuery.fn.enable_cropper();</script>'; //TODO: More elegant way to attach to file uploaded event needed
        $output .= '<div class="image-preview" style="max-width:960px; width: auto; height:auto;" data-test="">';
        $output .= theme('image', array('path' => 'public://'.$element['#file']->filename));
        $output .= '</div>';
    }

    $output .= '<div class="image-widget-data">';

    if ($element['fid']['#value'] != 0) {
        $element['filename']['#markup'] .= ' <span class="file-size">(' . format_size($element['#file']->filesize) . ')</span> ';
    }

    $output .= drupal_render_children($element);

    $output .= '</div>';
    $output .= '</div>';

    return $output;
}

/**
 * Implements hook_theme().
 */
function easy_frames_theme() {

    return array(
        'easy_frames_frame_upload' => array(
            'render element' => 'element',
            'file'           => 'easy_frames.module',
        )
    );
}

function easy_frames_frame_effect(&$image, $action = array()) {
    $frame_thickness = $action['frame_thickness'] / 100;
    $left = round($action['frame_left']);
    $top = round($action['frame_top']);
    $right = round($action['frame_right']);
    $bottom = round($action['frame_bottom']);
    $scale_factor = 1;
    module_load_include('inc', 'imagecache_actions', 'image_overlay');

    $file_uri = file_load($action['frame_image'])->uri;
    $overlay = image_load($file_uri);

    dpm($overlay);

    if ($overlay->info['width'] > $image->info['width'] || $overlay->info['height'] < $image->info['height']) {
        if ($overlay->info['width']/$image->info['width'] < $overlay->info['height']/$image->info['height']) {
            $scale_factor = $overlay->info['width'] / $image->info['width'] / $frame_thickness;
            image_scale($overlay, round($image->info['width'] * $frame_thickness), null, TRUE);
        } else {
            $scale_factor = $overlay->info['height'] / $image->info['height'];
            image_scale($overlay, null, round($image->info['height'] * $frame_thickness), TRUE);
        }
    }

    dpm ($overlay);
    dpm ('scale '.$scale_factor);

    if (!frame_resize($overlay,
        $image->info['width'],
        $image->info['height'],
        round($left/$scale_factor),
        round($top/$scale_factor),
        round($right/$scale_factor),
        round($bottom/$scale_factor)
    )
    ) {
        return FALSE;
    } else {
        echo "success";
    }

    return image_overlay($image, $overlay, 0, 0);
}

function frame_resize(&$image, $width, $height, $left = NULL,
                                               $top = NULL, $right = NULL, $bottom = NULL
) {
    $left = $left ? $left : 0;
    $top = $top ? $top : 0;
    $right = $right ? $right : $image->info['width'];
    $bottom = $bottom ? $bottom : $image->info['height'];


    $res = image_gd_create_tmp($image,$width,$height);

    // top-left
    if ($top > 0 && $left > 0 && !imagecopy($res, $image->resource, 0, 0, 0, 0, $left, $top)) {
        return FALSE;
    }



    // left
    if ($left > 0 && !imagecopyresampled($res, $image->resource,
            0,
            $top,
            0,
            $top,
            $left,
            $height - $bottom - $top,
            $left,
            $image->info['height'] - $bottom - $top
        )
    ) {
        return FALSE;
    }

    // top
    if ($top > 0 && !imagecopyresampled($res, $image->resource,
            $left,
            0,
            $left,
            0,
            $width - $right - $left,
            $top,
            $image->info['width'] - $right - $left,
            $top
        )
    ) {
        return FALSE;
    }

    // bottom-left
    if ($bottom < $image->info['height'] && $left > 0 && !imagecopy($res, $image->resource,
            0,
            $height - $bottom,
            0,
            $image->info['height'] - $bottom,
            $left,
            $image->info['height'] - $bottom
        )
    ) {
        return FALSE;
    }

    // bottom
    if ($bottom < $image->info['height'] && !imagecopyresampled($res, $image->resource,
            $left,
            $height - $bottom,
            $left,
            $image->info['height'] - $bottom,
            $width - $right - $left,
            $bottom,
            $image->info['width'] - $right - $left,
            $bottom
        )
    ) {
        return FALSE;
    }

    // bottom-right
    if ($bottom < $image->info['height'] && $right < $image->info['width'] &&
        !imagecopy($res, $image->resource,
            $width - $right,
            $height - $bottom,
            $image->info['width'] - $right,
            $image->info['height'] - $bottom,
            $image->info['width'] - $right,
            $image->info['height'] - $bottom
        )
    ) {
        return FALSE;
    }

    // right
    if ($right < $image->info['width'] && !imagecopyresampled($res, $image->resource,
            $width - $right,
            $top,
            $image->info['width'] - $right,
            $top,
            $right,
            $height - $bottom - $top,
            $right,
            $image->info['height'] - $bottom - $top
        )
    ) {
        return FALSE;
    }

    // top-right
    if ($top > 0 && $right < $image->info['width'] && !imagecopy($res, $image->resource,
            $width - $right,
            0,
            $image->info['width'] - $right,
            0,
            $width - $right,
            $top
        )
    ) {
        return FALSE;
    }

    // center
    if (!imagecopyresampled($res, $image->resource,
        $left,
        $top,
        $left,
        $top,
        $width - $right - $left,
        $height  - $bottom - $top,
        $image->info['width'] - $right - $left,
        $image->info['height'] - $bottom - $top
    )
    ) {
        return FALSE;
    }

    imagedestroy($image->resource);

    // Update image object.
    $image->resource = $res;
    $image->info['width'] = $width;
    $image->info['height'] = $height;

    return TRUE;
}

